# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 824b2fac33fcb384bbec71fdd7dbf5f7fe6b0d54221c709fa7dbb39d42b27cc872f6a78383f624792086ad99809c439456a465961b4ecc869de00b5aacb95cdf

test:
  secret_key_base: 4d74d40e027c7df7e898afbafb4c0afb9ddc5bebdb2a0a0fb63bd1d71e6beeb62d70d461c3c37f6cf53032ab6f7265a8170b5ddb976f4f975b9eac207b81b65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
